import React, { useState, useEffect } from "react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { db } from "../firebase";

function SuperAdminReport({ events, registrations }) {
  const [selectedEventId, setSelectedEventId] = useState("");
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [feedbackCount, setFeedbackCount] = useState(0);
  
  // Checkbox States
  const [options, setOptions] = useState({
    title: true,
    description: true,
    date: true,
    venue: true,
    time: true,
    organizers: true,
    totalReg: true,
    totalAttended: true,
    feedbacks: true,
    signature: true,
  });

  const handleCheckboxChange = (e) => {
    setOptions({ ...options, [e.target.name]: e.target.checked });
  };

  useEffect(() => {
    if (selectedEventId) {
      const ev = events.find((e) => e.id === selectedEventId);
      setSelectedEvent(ev);
      fetchFeedbackCount(selectedEventId);
    }
  }, [selectedEventId, events]);

  const fetchFeedbackCount = async (eventId) => {
    const q = query(collection(db, "feedbacks"), where("eventId", "==", eventId));
    const snap = await getDocs(q);
    setFeedbackCount(snap.size);
  };

  const handlePrint = () => {
    window.print();
  };

  // Calculations for report
  const eventRegs = registrations.filter(r => r.eventId === selectedEventId);
  const attendedCount = eventRegs.filter(r => r.checkInStatus).length;

  return (
    <div className="admin-section-card report-page-container">
      {/* CONFIGURATION SECTION (Hidden during print) */}
      <div className="report-config no-print">
        <div className="registration-controls">
          <label>1. Select Event</label>
          <select 
            value={selectedEventId} 
            onChange={(e) => setSelectedEventId(e.target.value)}
            className="admin-dropdown"
          >
            <option value="">-- Select Event --</option>
            {events.map(e => <option key={e.id} value={e.id}>{e.title}</option>)}
          </select>
        </div>

        <div className="options-grid">
          <label><input type="checkbox" name="title" checked={options.title} onChange={handleCheckboxChange} /> Event Title</label>
          <label><input type="checkbox" name="description" checked={options.description} onChange={handleCheckboxChange} /> Short Description</label>
          <label><input type="checkbox" name="date" checked={options.date} onChange={handleCheckboxChange} /> Event Date</label>
          <label><input type="checkbox" name="venue" checked={options.venue} onChange={handleCheckboxChange} /> Venue</label>
          <label><input type="checkbox" name="time" checked={options.time} onChange={handleCheckboxChange} /> Time</label>
          <label><input type="checkbox" name="organizers" checked={options.organizers} onChange={handleCheckboxChange} /> Organizers</label>
          <label><input type="checkbox" name="totalReg" checked={options.totalReg} onChange={handleCheckboxChange} /> Total Registered</label>
          <label><input type="checkbox" name="totalAttended" checked={options.totalAttended} onChange={handleCheckboxChange} /> Total Attended</label>
          <label><input type="checkbox" name="feedbacks" checked={options.feedbacks} onChange={handleCheckboxChange} /> Total Feedbacks</label>
          <label><input type="checkbox" name="signature" checked={options.signature} onChange={handleCheckboxChange} /> Signature Section</label>
        </div>

        {selectedEventId && (
          <button className="print-btn" onClick={handlePrint}>Generate & Print PDF</button>
        )}
      </div>

      {/* REPORT PREVIEW (The Actual Template) */}
      {selectedEventId ? (
        <div className="report-preview-paper" id="printable-report">
          <div className="report-header">
            <h1 className="report-main-title">EVENT COMPLETION REPORT</h1>
            <p className="report-subtitle">Generated by iBento SuperAdmin System</p>
          </div>

          <div className="report-body">
            {options.title && (
              <div className="report-item">
                <span className="label">Event Name:</span>
                <span className="value">{selectedEvent?.title}</span>
              </div>
            )}

            {options.organizers && (
              <div className="report-item">
                <span className="label">Organizing Body:</span>
                <span className="value">{selectedEvent?.clubId?.toUpperCase()}</span>
              </div>
            )}

            {(options.date || options.time || options.venue) && (
              <div className="report-row">
                {options.date && <div className="report-item"><strong>Date:</strong> {selectedEvent?.date}</div>}
                {options.time && <div className="report-item"><strong>Time:</strong> {selectedEvent?.time || "N/A"}</div>}
                {options.venue && <div className="report-item"><strong>Venue:</strong> {selectedEvent?.venue || "Main Campus"}</div>}
              </div>
            )}

            {options.description && (
              <div className="report-block">
                <h3>Event Description</h3>
                <p>{selectedEvent?.description || "No description provided."}</p>
              </div>
            )}

            <div className="report-stats-grid">
              {options.totalReg && (
                <div className="stat-box">
                  <p>Registered</p>
                  <strong>{eventRegs.length}</strong>
                </div>
              )}
              {options.totalAttended && (
                <div className="stat-box">
                  <p>Attended</p>
                  <strong>{attendedCount}</strong>
                </div>
              )}
              {options.feedbacks && (
                <div className="stat-box">
                  <p>Feedbacks</p>
                  <strong>{feedbackCount}</strong>
                </div>
              )}
            </div>

            {options.signature && (
              <div className="signature-area">
                <div className="sig-box">
                  <p>__________________________</p>
                  <span>Authorized Signatory</span>
                </div>
                <div className="sig-box">
                  <p>__________________________</p>
                  <span>Event Coordinator</span>
                </div>
              </div>
            )}
          </div>
          <div className="report-footer">
            <p>© {new Date().getFullYear()} iBento - Official Record</p>
          </div>
        </div>
      ) : (
        <div className="no-print no-selection-placeholder">
          <p>Please select an event to configure the report.</p>
        </div>
      )}
    </div>
  );
}

export default SuperAdminReport;